### ISSUE TITLE
Pointer commands

### ISSUE THREAD

**Issue by Soaku** [Soaku/Pepe#10]
The pointer section (4 E/e) has an awful lot of wasted space, mostly since there aren't that much pointer commands necessary. If I thought of this earlier, I would swap this section with I/O.

As first, these two commands could be useful - They can also work as a workaround for getting length of stack, as requested in #8.

- Flags: insert, prepend
  - [x] `EeeE` - Push pointer position.
  - [x] `Eeee` - Push reverse pointer position (0 = last stack item)

You could use them to get the size of stack while pointing the first or last item in the stack, with the help of `EEEE` and `EEEe`.

Next - input pointer commands. If the program accepts multiple inputs, these commands allow reuse of input stack items. `eeEE` and `eeEe` can also work as a workaround for checking the amount of input left, as requested in #6.

- [x] `eEEE` - Move input pointer to the first item.
- [x] `eEEe` - Move input pointer to the last item.
- [x] `eEeE` - Move input pointer to previous item.
- [x] `eEee` - Move input pointer to next item.
- [x] `eeEE` - Push input pointer position.
- [x] `eeEe` - Push amount of input items left (1 = last input item; 0 = end of input) – this will return a negative number if end of input was crossed.
- [x] `eeeE` - Lock input pointer - prevent automatic changing of the input pointer.
- [x] `eeee` - Unlock input pointer - allow automatic changing of the input pointer.

**Comment by u-ndefine** [comment]
Seems like I need the `EeeE` and `Eeee` commands already...

**Comment by Soaku** [comment]
Pointer position commands are now available in master. https://github.com/Soaku/Pepe/commit/3c57de931bd91fc91c61c9f33f916a3a961dbc75

**Comment by Soaku** [comment]
I'm bored and decided to work on this. I think it's complete, but... gee, Pepe needs a complete rewrite.
