### ISSUE TITLE
Active item from A B times

### ISSUE THREAD

**Issue by u-ndefine** [Soaku/Pepe#12]
**2 value = 6 E/e**

This is useful for repeated characters.

`[A, B] = [Output]`
`[32 (space), 3] = [32,32,32]`
`[any, 0] = [] (none)`
The command will be `EEEeee`.

**Comment by u-ndefine** [comment]
Now it looks like I need this, it's getting tedious to make while loops.

**Comment by Soaku** [comment]
Implemented! 

[And a sample program which I had to do, takes single number as argument](http://localhost:8000/#!b9!ajQ!p_bH)
