### ISSUE TITLE
max() and min() functions

### ISSUE THREAD

**Issue by u-ndefine** [Soaku/Pepe#19]
**It's been a long while, and I'm going back again.**
As of now, there have been no current implementation on these two functions: max() and min().
So I kindly request to have these 4 new commands:

## Full stack
* Min of full stack
* Max of full stack

## 2 Value
* min(a,b)
* max(a,b)

**Comment by Soaku** [comment]
Should be very easy to do. I'm currently busy doing one feature for one of my other projects, when I'm done I'll be happy to work on this.
