### ISSUE TITLE
Pepe - Functions need tests!

### ISSUE THREAD

**Issue by Soaku** [Soaku/Pepe#2]
Pepe is ready, but it hasn't been completely tested. I checked how some of them work, but they still might need a review. Like, they could have wrong behaviour when the stack is empty or when the selected item is 0 or negative. So I would ask you, the reader, to review them, even if the checkbox next to the function is checked. After reviewing, please, submit an answer showing what's good and what's wrong.

> Checked commands have been reviewed, at least partially. That doesn't mean still, that they can't have any bugs.
>
> The boxes under functions are test cases, checked = tested. 

- [x] Pushing *appends* an item to the stack
- [x] Popping removes the selected item
- [x] Pointer location is *never* changed, unless specified in function, or the position gets removed
- [x] Pointer doesn't wrap

### [1 E/e (2) Basic stack operations](https://github.com/Soaku/Pepe/projects/2#column-2205663)

- [x] `E` - [WS << push 0](https://github.com/Soaku/Pepe/projects/2#card-7485469)
  - [x] Does what it says
  - [x] Works for both stacks
- `e` - [WS >> Do nothing (pop)](https://github.com/Soaku/Pepe/projects/2#card-7485481)
  - [x] Does what it says
  - [x] Works for both stacks
  - [x] Does nothing if stack is empty

### [2 E/e (4) Program flow](https://github.com/Soaku/Pepe/projects/2#column-2172199)

> For every command in section: X is value of the selected item from WS.
>
> Goto commands don't do anything if corresponding labels don't exist.

- `EE` - [Create label with name X](https://github.com/Soaku/Pepe/projects/2#card-7338713)
  - [x] Does what it says
  - [x] Calling again with the same name will result in replacing previous label
  - [x] Works for both stacks
- `Ee` - [Return to where a goto was called last](https://github.com/Soaku/Pepe/projects/2#card-7339434)
  - [x] Does what it says
  - [x] Ignores the stack used
- `eE` - [Goto label X if active item == active item in the other stack](https://github.com/Soaku/Pepe/projects/2#card-7716208)
  - [x] Does what it says
  - [x] Works for both stacks
- `ee` - [Goto label X if active item != active item in the other stack](https://github.com/Soaku/Pepe/projects/2#card-7716960)
  - [x] Does what it says
  - [x] Works for both stacks

### [3 E/e (8) I/O](https://github.com/Soaku/Pepe/projects/2#column-2171797)

> If input is a string, every contained byte is pushed as an integer

- [x] Make sure only the selected item is popped, not the entire stack or the last item...

- `EEE` - [WS << Auto-parse input](https://github.com/Soaku/Pepe/projects/2#card-7337865)
  - [x] Works for ints
  - [x] Works for floats
  - [x] Works for negatives
  - [x] Works for strings (pushes charcodes)
- `EEe` - [WS << Parse input as string](https://github.com/Soaku/Pepe/projects/2#card-7337875)
  - [x] Works for strings (pushes charcodes)
  - [x] Ints and floats are parsed as strings (`123 -> "123"`)
- `EeE` - [WS << Parse input as integer](https://github.com/Soaku/Pepe/projects/2#card-7485918)
  - [x] Works for integers
  - [x] Floats are rounded first
  - [x] Works for negatives
  - [x] Strings result in 0
- `Eee` - [WS << Parse input as float](https://github.com/Soaku/Pepe/projects/2#card-7337874)
  - [x] Works for floats
  - [x] Works for negatives
  - [x] Strings result in 0
- `eEE` - [WS >> Output as number](https://github.com/Soaku/Pepe/projects/2#card-7344002)
  - [x] Prints ints
  - [x] Prints floats
  - [x] Works for negatives (at least for ints)
  - [x] Pops the stack
- `eEe` - [WS >> Output as character](https://github.com/Soaku/Pepe/projects/2#card-7337895)
  - [x] Prints characters
  - [x] Pops the stack
- `eeE` - [Output newline (`\n`)](https://github.com/Soaku/Pepe/projects/2#card-7501362)
  - [x] Outputs a newline
- `eee` - [Output WS content as string without popping](https://github.com/Soaku/Pepe/projects/2#card-7493465)
  - [x] Prints the entire stack contents

### [4 E/e (16) Pointer](https://github.com/Soaku/Pepe/projects/2#column-2171962)

*10 slots left*

- `EEEE` - [Move WS pointer to first item](https://github.com/Soaku/Pepe/projects/2#card-7337904)
  - [x] Works
- `EEEe` - [Move WS pointer to last item](https://github.com/Soaku/Pepe/projects/2#card-7337939)
  - [x] Works
- `EEeE` - [Rewind - Move WS pointer to previous item](https://github.com/Soaku/Pepe/projects/2#card-7337914)
  - [x] Works
- `EEee` - [Forward - Move WS pointer to next item](https://github.com/Soaku/Pepe/projects/2#card-7337906)
  - [x] Works
- `EeEE` - [Set position to random item](https://github.com/Soaku/Pepe/projects/2#card-7487437)
  - [x] Works
  - [x] Every item has an approximately equal appear chance - Seems to be true, unsure through
- `EeEe` - Empty (reserved for a `random` function)

### [5 E/e (32) Active item](https://github.com/Soaku/Pepe/projects/2#column-2173896)

*14 slots left*

- `EEEEE` - [Increment active item](https://github.com/Soaku/Pepe/projects/2#card-7338659)
  - [x] Works
- `EEEEe` - [Decrement active item](https://github.com/Soaku/Pepe/projects/2#card-7338662)
  - [x] Works
- `EEEeE` - [Duplicate active item (duplicate to next)](https://github.com/Soaku/Pepe/projects/2#card-7338639)
  - [x] Works
  - [x] Places the item on the next position to the pointer
- `EEEee` - [Push active item (duplicate to end)](https://github.com/Soaku/Pepe/projects/2#card-7338640)
  - [x] Works
  - [x] Places the item on the end
- `EEeEE` - [Random from 0 to active item value](https://github.com/Soaku/Pepe/projects/2#card-7486911)
  - [x] Works
  - [x] Works for negatives
- `EEeEe` - Empty (reserved for a `random` function)
- `EEeeE` - [Round active item](https://github.com/Soaku/Pepe/projects/2#card-7344007)
  - [x] Works
- `EEeee` - [Round active item to 0.5](https://github.com/Soaku/Pepe/projects/2#card-7487731)
  - [x] Works
  - [x] Works for negatives
- `EeEEE` - [Ceil active item](https://github.com/Soaku/Pepe/projects/2#card-7344020)
  - [x] Works
- `EeEEe` - [Floor active item](https://github.com/Soaku/Pepe/projects/2#card-7344011)
  - [x] Works
- `EeEeE` - [Absolute value of active item](https://github.com/Soaku/Pepe/projects/2#card-7485569)
  - [x] Works
  - [x] Works for negatives
- `EeEee` - [Reverse sign of active item (times -1)](https://github.com/Soaku/Pepe/projects/2#card-7344091)
  - [x] Works
- `EeeEE` - [Square - Raise active item to second power](https://github.com/Soaku/Pepe/projects/2#card-7487657)
  - [x] Works
- `EeeEe` - [Cube - Raise active item to third power](https://github.com/Soaku/Pepe/projects/2#card-7487662)
  - [x] Works
- `EeeeE` - [Square root of active item](https://github.com/Soaku/Pepe/projects/2#card-7488241)
  - [x] Works
  - [x] **BUG:** Negative values return `null`, should be `0`
- `Eeeee` - [Cube root of active item](https://github.com/Soaku/Pepe/projects/2#card-7488346)
  - [x] Works
  - [x] **BUG:** Returns large floats (no longer reproducible)
- `eEEEE` - [Modulo 2 of active item](https://github.com/Soaku/Pepe/projects/2#card-7708043)
  - [x] Works
- `eEEEe` - [Modulo 3 of active item](https://github.com/Soaku/Pepe/projects/2#card-7708024)
  - [x] Works

### [6 E/e (64) 2 value](https://github.com/Soaku/Pepe/projects/2#column-2172019)

*55 slots left*

> Commands operating on active items from both stacks.
>
> A = active item from WS, B = active item from the other stack

- [x] `EEEEEE` - [WS << A+B](https://github.com/Soaku/Pepe/projects/2#card-7338110)
- [x] `EEEEEe` - [WS << A-B](https://github.com/Soaku/Pepe/projects/2#card-7338448)
- [x] `EEEEeE` - [WS << A\*B](https://github.com/Soaku/Pepe/projects/2#card-7338506)
- [x] `EEEEee` - [WS << A/B](https://github.com/Soaku/Pepe/projects/2#card-7338512)
  - [x] **BUG**: Division by 0 returns null, should 0
- [x] `EEEeEE` - [WS << str(A)+str(B)](https://github.com/Soaku/Pepe/projects/2#card-7487145)
- [x] `EEEeEe` - [WS << A splitted every B digit](https://github.com/Soaku/Pepe/projects/2#card-7492924)
- [x] `EEEeeE` - [WS << B chunks of A](https://github.com/Soaku/Pepe/projects/2#card-7492793)
- [x] `EEEeee` - Empty
- [x] `EEeEEE` - [WS << A^B](https://github.com/Soaku/Pepe/projects/2#card-7487563)
- [x] `EEeEEe` - [WS << B'th root of A](https://github.com/Soaku/Pepe/projects/2#card-7487580)
- [x] `EEeEeE` - [WS << A%B (modulo)](https://github.com/Soaku/Pepe/projects/2#card-7708060)
- [x] `EEeEee` - Empty

### [7 E/e (128) Cross-stack](https://github.com/Soaku/Pepe/projects/2#column-2172008)

*121 slots left*

- [x] `EEEEEEE` - [Move active item to the other stack](https://github.com/Soaku/Pepe/projects/2#card-7338040)
- [x] `EEEEEEe` - [Copy active item to the other stack](https://github.com/Soaku/Pepe/projects/2#card-7338048)
- [x] `EEEEEeE` - [Move WS content to the other stack](https://github.com/Soaku/Pepe/projects/2#card-7338051)
- [x] `EEEEEee` - [Copy WS content to the other stack](https://github.com/Soaku/Pepe/projects/2#card-7338052)
- [x] `EEEEeEE` - [Reverse stack names (R = r; r = R)](https://github.com/Soaku/Pepe/projects/2#card-7344098)
- [x] `EEEEeEe` - Empty
- [x] `EEEEeeE` - [Diff - Remove items from WS that occur in the other stack](https://github.com/Soaku/Pepe/projects/2#card-7487263)
- [x] `EEEEeee` - [Reverse diff - Remove items from wS that **don't** occur in the other stack](https://github.com/Soaku/Pepe/projects/2#card-7487284)

### [8 E/e (256) Full stack](https://github.com/Soaku/Pepe/projects/2#column-2172176)

*246 slots left*

> Commands operating on the whole stack
>
> Unlike a lot of other commands, these don't clear the stack! [See information](https://github.com/Soaku/Pepe/projects/2#card-7488668)

- [x] `EEEEEEEE` - [Sum (+)](https://github.com/Soaku/Pepe/projects/2#card-7338609)
- [x] `EEEEEEEe` - Empty
- [x] `EEEEEEeE` - [Product (\*)](https://github.com/Soaku/Pepe/projects/2#card-7338613)
- [x] `EEEEEEee` -  Empty
- [x] `EEEEEeEE` - [Join](https://github.com/Soaku/Pepe/projects/2#card-7338617)
- [x] `EEEEEeEe` - Empty
- [x] `EEEEEeeE` - [Increment all](https://github.com/Soaku/Pepe/projects/2#card-7338669)
- [x] `EEEEEeee` - [Decrement all](https://github.com/Soaku/Pepe/projects/2#card-7338670)
- [x] `EEEEeEEE` - [Clear](https://github.com/Soaku/Pepe/projects/2#card-7338687)
- [x] `EEEEeEEe` - [Clear, but don't remove selected item](https://github.com/Soaku/Pepe/projects/2#card-7488515)
- [x] `EEEEeEeE` - [Sort](https://github.com/Soaku/Pepe/projects/2#card-7488771)
- [x] `EEEEeEee` - [Reverse order](https://github.com/Soaku/Pepe/projects/2#card-7344092)
- [x] `EEEEeeEE` - [Shuffle order](https://github.com/Soaku/Pepe/projects/2#card-7487499)

### [9 E/e (512) Characters](https://github.com/Soaku/Pepe/projects/2#column-2205901)

First letter:

- `E` - Push
- `e` - Print as character

Following letters are parsed as:

- `E` - 1
- `e` - 0

Converted to a binary number, then to a corresponding ASCII character.

Ex: To print `A`, the command would be `reEeeeeeeE`.

-------------------------------------------------------

Useful program for testing: [here](https://soaku.github.io/Pepe/#FO!o/). Takes all input (except if any is 0), change the 2nd command if needed and append the tested command.

**Comment by u-ndefine** [comment]
`EEeEE` works and changes active item, but negative numbers will reach -1 and will not change.
`EEEEe` also works.
`EEee` is also working and doesn't modify stack contents.

**Comment by Soaku** [comment]
@u-ndefine Sorry for such a late reply, didn't check Github at the time. From what I tested, the random operation is performed [a,b) - a is included, b is excluded. a is automatically set to the lower number, b to the higher. Because of this `2` can give 0 or 1, not 2 and `-2` can give -2 or -1, not 0.

**Comment by u-ndefine** [comment]
@Soaku I think I found the problem.

Either change code to
`Math.floor(...)` to `Math.round(...)`
or add an if-else statement for the negatives.

**Comment by u-ndefine** [comment]
`EE` - all check.
`eX` (X = E or e) - works in both stacks.
`EEEeX` - all check.

**Comment by u-ndefine** [comment]
4 E's: all check except `EeEE`; `EeEE` works but it's (not confirmed) unequal.
8 E's:
`EEEEeEee` and `EEEEeeEE` works.
`EEEEeEeE` sorts unusually; sorting `brown fox` outputs `fnoorwx b` instead of leading space then `bfnoorwx` [Test of EEEEeEeE](https://soaku.github.io/Pepe/#!c4!d0!cu!da!cs!8g!cc!cu!dc!kRuG)
`EEEEeEEE` works, but `EEEEeEEE` is weird. [Test of EEEEeEEE](https://soaku.github.io/Pepe/#!c4!d0!cu!da!cs!8g!cc!cu!dc!kRwG)

**Comment by Soaku** [comment]
@u-ndefine Both are fixed now. Thanks!

**Comment by u-ndefine** [comment]
8 E's: all check except product and decrement all.

`EEEEEEeE` Product (*): `0` instead of `1000` [(Test)](https://soaku.github.io/Pepe/#!78!78!78!kSa!oM)
`EEEEEeee` Decrement all: Stack is `[10,11,10]` instead of `[9,10,9]` [(Test)](https://soaku.github.io/Pepe/#!78!7a!78!kS0)

--------

Little question: How to request a new command?

**Comment by Soaku** [comment]
@u-ndefine Thanks! Fixed both.

You can create a new issue. If you want to suggest few similar commands you can do them all in one issue.

**Comment by u-ndefine** [comment]
Please check all the empty commands.
`eEEEE` doesn't do anything.

**Comment by u-ndefine** [comment]
Check all commands labeled _Empty._
`eEEEE` doesn't work.

**Comment by Soaku** [comment]
@u-ndefine Modulus now works.

All *Empty* are supposed to output their own name and "ERROR!". I guess there is no point in checking them, nobody is supposed to use them for anything anyway.

**Comment by Soaku** [comment]
**TODO:** Some command for checking if there's input left. Would be very useful for debugging and dynamic-length input. Gotta find a good slot first.
