### ISSUE TITLE
Goto if input left

### ISSUE THREAD

**Issue by Soaku** [Soaku/Pepe#6]
2 commands like this would be useful:

- goto if any input left
- goto if no input left

The problem is that there's no space left for such commands. A possibility would be to implement it as an `R` flag for existing `goto`s, but it breaks the idea of flags. Nah.

Another possibility would be to break backwards changes and add an actual flag `R` that would reverse the `goto`'s condition and replace current `ee` with `goto if input left`. Sounds like an idea, though versioning would be required to not break backwards compatibility and I have no idea how to do it.

**Comment by u-ndefine** [comment]
Maybe the `Ee`? (But this will ruin the `while...do` loop)

**Comment by Soaku** [comment]
I cannot accept this for now. It might be possible to add when versioning gets added.
