### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by u-ndefine** [Soaku/Pepe#8]
Commands I suggest:

- [ ] Length of stack **[8 E?]**
- [x] Left shift (1 << 2 = 4, 3 << 3 = 24, 0 << 2 = 2) **[6 E]**
- [x] Logical right shift (4 >>> 2 = 1, 10 >>> 1 = 5, 7 >> 2 = 1) **[6 E]**
- [x] Bit left shift (or n*2) **[5 E]**
- [x] Logical bit right shift (or floor(n/2)) **[5 E]**

**Comment by Soaku** [comment]
Ok, added. I didn't add length of stack yet since I can't find applicable slot. I'd try to add that in the future if there would be a possibility though.
