### ISSUE TITLE
Flags not working on full-stack commands

### ISSUE THREAD

**Issue by u-ndefine** [Soaku/Pepe#9]
[This program](https://soaku.github.io/Pepe/#RQ@&0-R@&0E7$!o&0@-Sa@F-jC/N) checks if 3 integers are distinct. (Input `a,b,c`; note change "separated by" box to `,`)

This should work but the flag in `rRrEEEEEEeE` doesn't seem to work.

**Comment by Soaku** [comment]
Looks like I've missed those commands together with some other. This should be easily fixed.
